name: Python CI / CD Settings

env:
  S3_BUCKET_NAME: real-time-stock-s3-bucket

on:
  push:
    branches:
      - main
      - '**'

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Make zip file
        run: zip -r ./realTime-stock.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region us-east-1 ./realTime-stock.zip s3://$S3_BUCKET_NAME/realTime-stock.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name realTime-stock --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name real-time-stock-deploy --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=realTime-stock.zip
